# Generated by Django 5.1.6 on 2025-03-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('others', 'Others'), ('team_lead', 'Team Lead')], default='others', max_length=20),
        ),
    ]
