# Generated by Django 5.1.6 on 2025-03-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
