# Generated by Django 5.1.6 on 2025-03-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_clubmembership_role_approvedmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.CharField(default='price', max_length=255),
            preserve_default=False,
        ),
    ]
