# Generated by Django 5.1.6 on 2025-03-16 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
