# Generated by Django 5.1.6 on 2025-03-23 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_chatsession_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
